apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  targetNamespace: podinfo
  path: ./kubernetes/apps/default/podinfo/kustomization.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: default
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: podinfo
  timeout: 1m